file = {
    SOI ~
    (property | section_data | NEWLINE)*
    ~ EOI
}

section_data = { section ~ property* } 

section = { "[" ~ name ~ "]" ~ (NEWLINE | EOI) }
property = { name ~ white_space* ~ "=" ~ white_space* ~ value ~ white_space*  ~ (NEWLINE | EOI) }

name = { char+ }
value = { char* }

char = _{ ASCII_ALPHANUMERIC | "." | "_" | "/"  | white_space }
white_space = _{ "\t" | " " }

// This allows comments starting with ';' until the end of the line
COMMENT = _{ ";" ~ (!NEWLINE ~ ANY)* }